// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// NewGetIpamIPDetectionConfigsParams creates a new GetIpamIPDetectionConfigsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIpamIPDetectionConfigsParams() *GetIpamIPDetectionConfigsParams {
	return &GetIpamIPDetectionConfigsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIpamIPDetectionConfigsParamsWithTimeout creates a new GetIpamIPDetectionConfigsParams object
// with the ability to set a timeout on a request.
func NewGetIpamIPDetectionConfigsParamsWithTimeout(timeout time.Duration) *GetIpamIPDetectionConfigsParams {
	return &GetIpamIPDetectionConfigsParams{
		timeout: timeout,
	}
}

// NewGetIpamIPDetectionConfigsParamsWithContext creates a new GetIpamIPDetectionConfigsParams object
// with the ability to set a context for a request.
func NewGetIpamIPDetectionConfigsParamsWithContext(ctx context.Context) *GetIpamIPDetectionConfigsParams {
	return &GetIpamIPDetectionConfigsParams{
		Context: ctx,
	}
}

// NewGetIpamIPDetectionConfigsParamsWithHTTPClient creates a new GetIpamIPDetectionConfigsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIpamIPDetectionConfigsParamsWithHTTPClient(client *http.Client) *GetIpamIPDetectionConfigsParams {
	return &GetIpamIPDetectionConfigsParams{
		HTTPClient: client,
	}
}

/*
GetIpamIPDetectionConfigsParams contains all the parameters to send to the API endpoint

	for the get ipam IP detection configs operation.

	Typically these are written to a http.Request.
*/
type GetIpamIPDetectionConfigsParams struct {

	// GetIPDetectionConfig.
	GetIPDetectionConfig *models.GetIPDetectionConfigArgs

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ipam IP detection configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIpamIPDetectionConfigsParams) WithDefaults() *GetIpamIPDetectionConfigsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get ipam IP detection configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIpamIPDetectionConfigsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) WithTimeout(timeout time.Duration) *GetIpamIPDetectionConfigsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) WithContext(ctx context.Context) *GetIpamIPDetectionConfigsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) WithHTTPClient(client *http.Client) *GetIpamIPDetectionConfigsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGetIPDetectionConfig adds the getIPDetectionConfig to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) WithGetIPDetectionConfig(getIPDetectionConfig *models.GetIPDetectionConfigArgs) *GetIpamIPDetectionConfigsParams {
	o.SetGetIPDetectionConfig(getIPDetectionConfig)
	return o
}

// SetGetIPDetectionConfig adds the getIpDetectionConfig to the get ipam IP detection configs params
func (o *GetIpamIPDetectionConfigsParams) SetGetIPDetectionConfig(getIPDetectionConfig *models.GetIPDetectionConfigArgs) {
	o.GetIPDetectionConfig = getIPDetectionConfig
}

// WriteToRequest writes these params to a swagger request
func (o *GetIpamIPDetectionConfigsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.GetIPDetectionConfig != nil {
		if err := r.SetBodyParam(o.GetIPDetectionConfig); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
