// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// GetIpamIPDetectionConfigsOKCode is the HTTP code returned for type GetIpamIPDetectionConfigsOK
const GetIpamIPDetectionConfigsOKCode int = 200

/*
GetIpamIPDetectionConfigsOK Success

swagger:response getIpamIpDetectionConfigsOK
*/
type GetIpamIPDetectionConfigsOK struct {

	/*
	  In: Body
	*/
	Payload *models.IPDetectionConfigs `json:"body,omitempty"`
}

// NewGetIpamIPDetectionConfigsOK creates GetIpamIPDetectionConfigsOK with default headers values
func NewGetIpamIPDetectionConfigsOK() *GetIpamIPDetectionConfigsOK {

	return &GetIpamIPDetectionConfigsOK{}
}

// WithPayload adds the payload to the get ipam Ip detection configs o k response
func (o *GetIpamIPDetectionConfigsOK) WithPayload(payload *models.IPDetectionConfigs) *GetIpamIPDetectionConfigsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ipam Ip detection configs o k response
func (o *GetIpamIPDetectionConfigsOK) SetPayload(payload *models.IPDetectionConfigs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIpamIPDetectionConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetIpamIPDetectionConfigsFailureCode is the HTTP code returned for type GetIpamIPDetectionConfigsFailure
const GetIpamIPDetectionConfigsFailureCode int = 500

/*
GetIpamIPDetectionConfigsFailure Config not initialized successfully or others

swagger:response getIpamIpDetectionConfigsFailure
*/
type GetIpamIPDetectionConfigsFailure struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetIpamIPDetectionConfigsFailure creates GetIpamIPDetectionConfigsFailure with default headers values
func NewGetIpamIPDetectionConfigsFailure() *GetIpamIPDetectionConfigsFailure {

	return &GetIpamIPDetectionConfigsFailure{}
}

// WithPayload adds the payload to the get ipam Ip detection configs failure response
func (o *GetIpamIPDetectionConfigsFailure) WithPayload(payload models.Error) *GetIpamIPDetectionConfigsFailure {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ipam Ip detection configs failure response
func (o *GetIpamIPDetectionConfigsFailure) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIpamIPDetectionConfigsFailure) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
