// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetIpamIPDetectionConfigsHandlerFunc turns a function with the right signature into a get ipam IP detection configs handler
type GetIpamIPDetectionConfigsHandlerFunc func(GetIpamIPDetectionConfigsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIpamIPDetectionConfigsHandlerFunc) Handle(params GetIpamIPDetectionConfigsParams) middleware.Responder {
	return fn(params)
}

// GetIpamIPDetectionConfigsHandler interface for that can handle valid get ipam IP detection configs params
type GetIpamIPDetectionConfigsHandler interface {
	Handle(GetIpamIPDetectionConfigsParams) middleware.Responder
}

// NewGetIpamIPDetectionConfigs creates a new http.Handler for the get ipam IP detection configs operation
func NewGetIpamIPDetectionConfigs(ctx *middleware.Context, handler GetIpamIPDetectionConfigsHandler) *GetIpamIPDetectionConfigs {
	return &GetIpamIPDetectionConfigs{Context: ctx, Handler: handler}
}

/*
	GetIpamIPDetectionConfigs swagger:route GET /ipam/ip-detection-configs daemonset getIpamIpDetectionConfigs

# Get ip-detection-configs for ip confilict and gateway detection

Get ip-detection-configs for ip confilict and gateway detection
*/
type GetIpamIPDetectionConfigs struct {
	Context *middleware.Context
	Handler GetIpamIPDetectionConfigsHandler
}

func (o *GetIpamIPDetectionConfigs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetIpamIPDetectionConfigsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
