// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetIPDetectionConfigArgs Get IP Conflict and Gateway detection Args
//
// swagger:model GetIPDetectionConfigArgs
type GetIPDetectionConfigArgs struct {

	// pod name
	PodName string `json:"podName,omitempty"`

	// pod namespace
	PodNamespace string `json:"podNamespace,omitempty"`
}

// Validate validates this get IP detection config args
func (m *GetIPDetectionConfigArgs) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get IP detection config args based on context it is used
func (m *GetIPDetectionConfigArgs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetIPDetectionConfigArgs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetIPDetectionConfigArgs) UnmarshalBinary(b []byte) error {
	var res GetIPDetectionConfigArgs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
