// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IPDetectionConfigs IPAM IP detection configs
//
// swagger:model IPDetectionConfigs
type IPDetectionConfigs struct {

	// enable gateway detection
	EnableGatewayDetection bool `json:"enableGatewayDetection,omitempty"`

	// enable IP conflict detection
	EnableIPConflictDetection bool `json:"enableIPConflictDetection,omitempty"`
}

// Validate validates this IP detection configs
func (m *IPDetectionConfigs) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this IP detection configs based on context it is used
func (m *IPDetectionConfigs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPDetectionConfigs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPDetectionConfigs) UnmarshalBinary(b []byte) error {
	var res IPDetectionConfigs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
